export default [
  {
    id: 0,
    title: "리액트 모각코 하실 분",
    content: "모각코 구함요",
    icon: "React",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: true,
  },
  {
    id: 1,
    title: "리액트 하실 분",
    content: "리액트 구함요",
    icon: "React",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: true,
  },
  {
    id: 2,
    title: "같이 자바스크립트하실 분",
    content: "자바스크립트 구함요",
    icon: "JS",
    meetingpoint: "서울 종로구 선원로 코워킹스페이스",
    date: " 2022년 3월 20일 오후 8시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: false,
  },
  {
    id: 3,
    title: "같이 파이선 하실 분",
    content: "파이선 구함요",
    icon: "Python",
    meetingpoint: "서울 성북구 전원로 카페 에녹",
    date: " 2022년 3월 21일 오후 3시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: true,
  },
  {
    id: 4,
    title: "같이 코틀린 하실 분",
    content: "코틀린 구함요",
    icon: "Kotlin",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: false,
  },
  {
    id: 5,
    title: "같이 타입스크립트 하실 분",
    content: "타입스크립트 구함요",
    icon: "TS",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: false,
  },
  {
    id: 6,
    title: "같이 고 하실 분",
    content: "고 구함요",
    icon: "Go",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    online: false,
  },
  {
    id: 7,
    title: "같이 고고 하실 분",
    content: "고고 구함요",
    icon: "Go",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    online: true,
  },
  {
    id: 8,
    title: "같이 자바스크립트 하실 분",
    content: "자바스크립트 구함요",
    icon: "JS",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: false,
  },
  {
    id: 9,
    title: "같이 타입스크립트 하실 분",
    content: "타입스크립트 구함요",
    icon: "TS",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: false,
  },
  {
    id: 10,
    title: "같이 파이선 하실 분",
    content: "파이선 구함요",
    icon: "Python",
    meetingpoint: "서울 성북구 전원로 카페 에녹",
    date: " 2022년 3월 21일 오후 3시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: true,
  },
  {
    id: 11,
    title: "같이 타입스크립트 하실 분",
    content: "타입스크립트 구함요",
    icon: "TS",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: true,
  },
  {
    id: 12,
    title: "같이 코틀린 하실 분",
    content: "코틀린 구함요",
    icon: "Kotlin",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트,",
    online: false,
  },
  {
    id: 13,
    title: "같이 고고 하실 분",
    content: "고고 구함요",
    icon: "Go",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트, 타이포그래피, 레이아웃 같은 그래픽 요소나 시각적 연출을 보여줄 때 사용하는 표준 채우기 텍스트로, 최종 결과물에 들어가는 실제적인 문장 내용이 채워지기 전에 시각 디자인 프로젝트 모형의 채움 글로도 이용된다. 이런 용도로 사용할 때 로렘 입숨을 그리킹(greeking)이라고도 부르며, 때로 로렘 입숨은 공간만 차지하는 무언가를 지칭하는 용어로도 사용된다.",
    online: false,
  },
  {
    id: 14,
    title: "같이 코틀린 하실 분",
    content: "코틀린 구함요",
    icon: "Kotlin",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트, 타이포그래피, 레이아웃 같은 그래픽 요소나 시각적 연출을 보여줄 때 사용하는 표준 채우기 텍스트로, 최종 결과물에 들어가는 실제적인 문장 내용이 채워지기 전에 시각 디자인 프로젝트 모형의 채움 글로도 이용된다. 이런 용도로 사용할 때 로렘 입숨을 그리킹(greeking)이라고도 부르며, 때로 로렘 입숨은 공간만 차지하는 무언가를 지칭하는 용어로도 사용된다.",
    online: false,
  },
  {
    id: 15,
    title: "같이 자바스크립트 하실 분",
    content: "자바스크립트 구함요",
    icon: "JS",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트, 타이포그래피, 레이아웃 같은 그래픽 요소나 시각적 연출을 보여줄 때 사용하는 표준 채우기 텍스트로, 최종 결과물에 들어가는 실제적인 문장 내용이 채워지기 전에 시각 디자인 프로젝트 모형의 채움 글로도 이용된다. 이런 용도로 사용할 때 로렘 입숨을 그리킹(greeking)이라고도 부르며, 때로 로렘 입숨은 공간만 차지하는 무언가를 지칭하는 용어로도 사용된다.",
    online: true,
  },
  {
    id: 16,
    title: "같이 타입 하실 분",
    content: "타입 구함요",
    icon: "TS",
    meetingpoint: "서울 서대문구 오량길 선선카페",
    date: "2022년 3월 18일 오후 6시",
    contnet:
      "로렘 입숨(lorem ipsum; 줄여서 립숨, lipsum)은 출판이나 그래픽 디자인 분야에서 폰트, 타이포그래피, 레이아웃 같은 그래픽 요소나 시각적 연출을 보여줄 때 사용하는 표준 채우기 텍스트로, 최종 결과물에 들어가는 실제적인 문장 내용이 채워지기 전에 시각 디자인 프로젝트 모형의 채움 글로도 이용된다. 이런 용도로 사용할 때 로렘 입숨을 그리킹(greeking)이라고도 부르며, 때로 로렘 입숨은 공간만 차지하는 무언가를 지칭하는 용어로도 사용된다.",
    online: true,
  },
];
